#
# Cookbook Name:: logentries
# Recipe:: default
#
# Copyright 2012, HipSnip Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Make sure a Token has been set
# @TODO: Better ways to Error out in Chef?
raise 'You have to set a Logentries Token in the attribute [:logentries][:token]' if node['logentries']['token'].empty?


# Some systems that run Rsyslog don't use an "rsyslog.d" folder - let's fix that!
if not ::File.exists? "/etc/rsyslog.d"
  directory "/etc/rsyslog.d" do
    owner "root"
    group "root"
    mode "0755"
    action :create
  end

  ruby_block "rsyslog_include_d_configs" do
    block do
      ::File.open "/etc/rsyslog.conf", "a" do |io|
        io.write "
        # Generated by chef
        $IncludeConfig /etc/rsyslog.d/*.conf"
      end
    end
    action :create
  end
end

if node['logentries']['enable_tls']
  package 'rsyslog-gnutls' do
    action :install
  end

  cookbook_file '/etc/syslog.logentries.crt' do
    source   'logentries.crt'
    mode     0644
  end
end

# Add logentries to all syslog entries for now
template "/etc/rsyslog.d/10-logentries.conf" do
  source "rsyslog-main.erb"
  mode "0644"
  notifies :restart, "service[rsyslog]"
end